version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    environment:
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    
  init_resources:
    build: .
    container_name: ml_engineering_resources
    image: ml_engineering_resources
    command: make
    depends_on:
        - localstack

  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - init_resources
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.job-run.train.schedule: "@every 5s" #TODO 3: Update as you see fit
      ofelia.job-run.train.command: "make train"
      ofelia.job-run.train.image: "ml_engineering_resources"
      ofelia.job-run.train.environment: USERNAME=test
      ofelia.job-run.inference.schedule: "@every 5s" #TODO 4: Update as you see fit
      ofelia.job-run.inference.command: "make inference"
      ofelia.job-run.inference.image: "ml_engineering_resources"
      ofelia.job-run.inference.environment: USERNAME=test
