name: YourNewModel
version: 0.0.1
features:
  - source: "data/train_A.csv"
    columns: 
      - name: "hotel_id"
        type: "string"
        xteristics:
          unique: true
      - name: "date"
        type: "datetime"
        xteristics:
          from_date: "2018-01-01"
          to_date: "2022-05-31"
      - name: "check_in"
        type: "datetime"
        xteristics:
          from_date: "2018-01-01"
          to_date: "2022-06-30"
      - name: "check_out"
        type: "datetime"
        xteristics:
          from_date: "2018-01-01"
          to_date: "2022-07-31"
      - name: "day_distance"
        type: "integer"
        xteristics:
          calculated: true
          calculated_columns: ["date", check_in"]
      - name: "length_of_stay"
        type: "integer"
        xteristics:
          calculated: true
          calculated_columns: ["check_in", "check_out"]
      - name: "status"
        type: "string"
        xteristics:
          values: ["booked", "cancelled", "fulfilled"]

  - source: "data/train_B.csv"
    columns: 
    - name: "hotel_id"
      type: "string"
      xteristics:
          unique: true
    - name: "country_code"
      type: "string"
      xteristics:
          length: 2

model:
  name: YourNewModel
  path: some-model-store
  training_script: train.py
  inference_script: inference.py
